services:
  gateway:
    image: gateway:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Gateway/Dockerfile

  catalog-api:
    image: catalog-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Catalog.API/Dockerfile

  review-api:
    image: review-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Review.API/Dockerfile

  photostock-api:
    image: photostock-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.PhotoStock.API/Dockerfile

  basket-api:
    image: basket-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Basket.API/Dockerfile


  order-api:
    image: order-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Order.API/Dockerfile

  payment-api:
    image: payment-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Payment.API/Dockerfile

  invoice-api:
    image: invoice-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Invoice.API/Dockerfile

  campaign-api:
    image: campaign-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Campaign.API/Dockerfile

  webui:
    image: webui:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.WebUI/Dockerfile
