services:
  gateway:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/gateway:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Gateway/Dockerfile

  catalog-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/catalog-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Catalog.API/Dockerfile

  search-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/search-api:${IMAGE_TAG:-latest}
    build:
      context: GameGaraj.Search.API
      dockerfile: Dockerfile

  review-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/review-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Review.API/Dockerfile

  photostock-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/photostock-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.PhotoStock.API/Dockerfile

  basket-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/basket-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Basket.API/Dockerfile


  order-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/order-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Order.API/Dockerfile

  payment-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/payment-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Payment.API/Dockerfile

  invoice-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/invoice-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Invoice.API/Dockerfile

  notification-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/notification-api:${IMAGE_TAG:-latest}
    build:
      context: GameGaraj.Notification.API
      dockerfile: Dockerfile

  campaign-api:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/campaign-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.Campaign.API/Dockerfile

  webui:
    image: ${IMAGE_REPOSITORY:-ghcr.io/kadir-yilmaz/gamegaraj}/webui:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: GameGaraj.WebUI/Dockerfile
