services:
  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: GameGaraj.Gateway/Dockerfile

  catalog-api:
    image: catalog-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Catalog.API/Dockerfile

  photostock-api:
    image: photostock-api:latest
    build:
      context: .
      dockerfile: GameGaraj.PhotoStock.API/Dockerfile

  basket-api:
    image: basket-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Basket.API/Dockerfile

  discount-api:
    image: discount-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Discount.API/Dockerfile

  order-api:
    image: order-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Order.API/Dockerfile

  payment-api:
    image: payment-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Payment.API/Dockerfile

  invoice-api:
    image: invoice-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Invoice.API/Dockerfile

  campaign-api:
    image: campaign-api:latest
    build:
      context: .
      dockerfile: GameGaraj.Campaign.API/Dockerfile

  webui:
    image: webui:latest
    build:
      context: .
      dockerfile: GameGaraj.WebUI/Dockerfile
