apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-controlplane-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kadir-yilmaz/GameGaraj.git
    targetRevision: main
    path: helm/controlplane-apps # Bu klasördeki tüm yaml dosyalarını okur
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Uygulamaların uygulaması olduğu için argocd namespace'ine kurar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
