version: "3.8"

services:
  discount-api:
    image: discount-api:latest
    ports:
      - "31012:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQUrl=host.docker.internal
      - IdentityOption__Authority=http://host.docker.internal:8080/realms/GameGaraj
      - ElasticSearchSettings__Uri=http://host.docker.internal:9201
      - ConnectionStrings__PostgreSql=User ID=admin;Password=Password12*;Server=host.docker.internal;Port=5432;Database=discountdb;Pooling=true
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
