version: "3.8"

services:
  order-api:
    image: order-api:latest
    ports:
      - "31013:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQUrl=host.docker.internal
      - IdentityOption__Authority=http://host.docker.internal:8080/realms/GameGaraj
      - ElasticSearchSettings__Uri=http://host.docker.internal:9201
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=GameGarajOrderDb;User Id=sa;Password=Password12*;TrustServerCertificate=True
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
