version: "3.8"

services:
  webui:
    image: webui:latest
    ports:
      - "31075:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMQUrl=host.docker.internal
      - IdentityOption__Authority=http://host.docker.internal:8080/realms/GameGaraj
      - ElasticSearchSettings__Uri=http://host.docker.internal:9201
      - APP_VERSION=GITHUB_SHA_PLACEHOLDER
      - ServiceApiSettings__GatewayBaseUri=http://gateway:8080
      - ServiceApiSettings__CatalogUri=http://catalog-api:8080/api
      - ServiceApiSettings__BasketUri=http://basket-api:8080/api/v1
      - ServiceApiSettings__PhotoStockUri=http://photostock-api:8080
      - ServiceApiSettings__DiscountUri=http://discount-api:8080/api
      - ServiceApiSettings__PaymentUri=http://payment-api:8080/api
      - ServiceApiSettings__OrderUri=http://order-api:8080
      - ServiceApiSettings__CampaignUri=http://campaign-api:8080/api
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
