apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-api
  labels:
    app: campaign-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign-api
  template:
    metadata:
      labels:
        app: campaign-api
    spec:
      containers:
      - name: campaign-api
        image: campaign-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: RabbitMQUrl
          value: "host.docker.internal"
        - name: IdentityOption__Authority
          value: "http://host.docker.internal:8080/realms/GameGaraj"
        - name: ElasticSearchSettings__Uri
          value: "http://host.docker.internal:9201"
        - name: ConnectionStrings__SqlServer
          value: "Server=host.docker.internal,1434;Database=CampaignDb;User Id=sa;Password=Password12*;TrustServerCertificate=true"
---
apiVersion: v1
kind: Service
metadata:
  name: campaign-api
spec:
  type: NodePort
  selector:
    app: campaign-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30016
