apiVersion: apps/v1
kind: Deployment
metadata:
  name: photostock-api
  labels:
    app: photostock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photostock-api
  template:
    metadata:
      labels:
        app: photostock-api
    spec:
      containers:
        - name: photostock-api
          image: photostock-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            # ASP.NET
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            # INTERNAL SERVICES (k3s içinde güvenli değil ama senin setup)
            - name: RabbitMQUrl
              value: "rabbitmq:5672"

            - name: IdentityOption__Authority
              value: "http://identity:8080/realms/GameGaraj"

            - name: ElasticSearchSettings__Uri
              value: "http://elasticsearch:9200"

            # =========================
            # MINIO (FIXED SECTION)
            # =========================
            - name: Minio__Endpoint
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: minio-endpoint

            - name: Minio__AccessKey
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: minio-access-key

            - name: Minio__SecretKey
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: minio-secret-key

            - name: Minio__BucketName
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: minio-bucket-name

            - name: Minio__Secure
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: minio-secure

---
apiVersion: v1
kind: Service
metadata:
  name: photostock-api
spec:
  type: NodePort
  selector:
    app: photostock-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30015
