apiVersion: apps/v1
kind: Deployment
metadata:
  name: photostock-api
  labels:
    app: photostock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photostock-api
  template:
    metadata:
      labels:
        app: photostock-api
    spec:
      containers:
      - name: photostock-api
        image: photostock-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: RabbitMQUrl
          value: "host.docker.internal"
        - name: IdentityOption__Authority
          value: "http://host.docker.internal:8080/realms/GameGaraj"
        - name: ElasticSearchSettings__Uri
          value: "http://host.docker.internal:9201"
        volumeMounts:
        - mountPath: /app/wwwroot/photos
          name: photostock-storage
      volumes:
      - name: photostock-storage
        hostPath:
          path: /home/kadirserver/gamegaraj/photos
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: photostock-api
spec:
  type: NodePort
  selector:
    app: photostock-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30015
