apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: webui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: RabbitMQUrl
          value: "host.docker.internal"
        - name: IdentityOption__Authority
          value: "http://host.docker.internal:8080/realms/GameGaraj"
        - name: ServiceApiSettings__IdentityBaseUri
          value: "https://keycloak.kadiryilmaz.online/realms/GameGaraj"
        - name: KEYCLOAK_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gamegaraj-secrets
              key: keycloak-admin-username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gamegaraj-secrets
              key: keycloak-admin-password
        - name: ADMIN_EMAIL
          value: "kadiryilmaz.dev@gmail.com"
        - name: ADMIN_PASSWORD
          value: "Kadir+1234"
        - name: ElasticSearchSettings__Uri
          value: "http://host.docker.internal:9201"
        - name: APP_VERSION
          value: "GITHUB_SHA_PLACEHOLDER"
        - name: ServiceApiSettings__GatewayBaseUri
          value: "http://gateway:8080"
        - name: ServiceApiSettings__CatalogUri
          value: "http://catalog-api:8080/api"
        - name: ServiceApiSettings__BasketUri
          value: "http://basket-api:8080/api/v1"
        - name: ServiceApiSettings__PhotoStockUri
          value: "http://photostock-api:8080"
        - name: ServiceApiSettings__PhotoBaseUrl
          value: "https://minio.kadiryilmaz.online/gamegaraj"
        - name: ServiceApiSettings__DiscountUri
          value: "http://discount-api:8080/api"
        - name: ServiceApiSettings__PaymentUri
          value: "http://payment-api:8080/api"
        - name: ServiceApiSettings__OrderUri
          value: "http://order-api:8080"
        - name: ServiceApiSettings__CampaignUri
          value: "http://campaign-api:8080/api"
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: NodePort
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30075
