{{- if .Values.configMaps.redisSentinel.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gamegaraj-redis-sentinel
  labels:
    {{- include "gamegaraj.labels" . | nindent 4 }}
data:
  sentinel1.conf: |
    {{- .Files.Get "config/sentinel1.conf" | nindent 4 }}
  sentinel2.conf: |
    {{- .Files.Get "config/sentinel2.conf" | nindent 4 }}
  sentinel3.conf: |
    {{- .Files.Get "config/sentinel3.conf" | nindent 4 }}
{{- end }}
