{{- if .Values.configMaps.realm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gamegaraj-keycloak-realm
  labels:
    {{- include "gamegaraj.labels" . | nindent 4 }}
data:
  realm-init.json: |
    {{- .Files.Get "config/realm-init.json" | nindent 4 }}
{{- end }}
