apiVersion: v1
kind: Secret
metadata:
  name: gamegaraj-secrets
  labels:
    {{- include "gamegaraj.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if ne (toString $value) "" }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
