{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- include "gamegaraj.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        gamegaraj.io/grafana-dashboard-version: "dashboards-v12-checkout-count-rps"
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: {{ .Values.monitoring.grafana.image }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamegaraj-secrets
                  key: grafana-admin-password
                  optional: true
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 256Mi
              cpu: 300m
            requests:
              memory: 128Mi
              cpu: 50m
          volumeMounts:
            - name: datasource-volume
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provisioning-volume
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboard-json-volume
              mountPath: /var/lib/grafana/dashboards
            - name: alerting-volume
              mountPath: /etc/grafana/provisioning/alerting
            - name: storage-volume
              mountPath: /var/lib/grafana
      volumes:
        - name: datasource-volume
          configMap:
            name: grafana-datasources
        - name: dashboard-provisioning-volume
          configMap:
            name: grafana-dashboard-provisioning
        - name: dashboard-json-volume
          configMap:
            name: grafana-dashboards
        - name: alerting-volume
          configMap:
            name: grafana-alerting
        - name: storage-volume
          {{- if .Values.monitoring.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: grafana-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}

