{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- include "gamegaraj.labels" $ | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: 15s
          queryTimeout: 30s
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger
            - name: TraceId
              datasourceUid: jaeger
            - name: TraceID
              datasourceUid: jaeger
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        uid: jaeger
{{- end }}
