name: Deploy To Home Server (K3s)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy To Server K3s
    runs-on: self-hosted

    env:
      KUBECONFIG: /home/kadirserver/.kube/config

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Verify Tooling
      run: |
        docker version
        kubectl version --client
        kubectl get nodes

    - name: Build Application Images
      run: |
        docker compose -f docker-compose.build.yml build

    - name: Apply Application Manifests
      run: |
        # Extract the short SHA for image tags / versioning
        shortSha=$(git rev-parse --short HEAD)
        sed -i "s/GITHUB_SHA_PLACEHOLDER/$shortSha/g" k8s/webui.yaml
        
        kubectl apply -f k8s/

    - name: Restart Deployments (Rolling Update)
      run: |
        kubectl rollout restart deployment

    - name: Post Deploy Checks
      run: |
        kubectl get deployments -o wide
        kubectl get pods -o wide
        kubectl get services -o wide
